### ISSUE TITLE
Unable to run node initlangs.js without error

### ISSUE THREAD

**Issue by Ankatic** [eslachance/etiket#4]
Hi,

Thanks for creating this project. It’ll definitely help my server and I once I get it working.

When I run node initlangs.js I get

(node:2305) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: not authorized on enmap to execute command { find: "langs", filter: {} }
(node:2305) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I followed all of the instructions, and I was wondering if there is anything I can do to get around this.

Thanks in advance,

Ankatic.

**Comment by eslachance** [comment]
That's a problem with your mongodb user not having the right to do something. It's not the code, it's your access to mongo that's the issue.
